name:                kuh
version:             0.1.0.0
github:              "rabuu/kuh"
license:             BSD-3-Clause
author:              "Rasmus Buurman"
maintainer:          "rasmus@rbuurman.de"
copyright:           "2024 Rasmus Buurman"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rabuu/kuh#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- diagrams-lib
- diagrams-svg

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  kuh:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kuh

tests:
  kuh-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kuh
